# Generated by Django 5.1.7 on 2025-05-25 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='filename',
            field=models.CharField(default='model_1ee71b97a71340d8a4af50d57e3e797b', max_length=150, unique=True),
        ),
    ]
