# Generated by Django 5.1.7 on 2025-06-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_alter_model3d_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='file',
            field=models.FileField(upload_to='stl_files/'),
        ),
        migrations.AlterField(
            model_name='model3d',
            name='filename',
            field=models.CharField(default='model_f098b08dd8474f46be3dd7d5f1b2113b', max_length=150, unique=True),
        ),
    ]
