# Generated by Django 5.1.7 on 2025-06-09 20:47

import prints.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0003_alter_model3d_file_alter_model3d_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='filename',
            field=models.CharField(default=prints.models.generate_filename, max_length=150, unique=True),
        ),
    ]
